FROM bellsoft/liberica-openjdk-alpine:17.0.2-9-x86_64

COPY target/RegistrationServer-0.0.1-SNAPSHOT.jar /RegistrationServer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/RegistrationServer-0.0.1-SNAPSHOT.jar"]