version: "3"
services:
      
  registration-service:
    image: registration-server:latest
    ports:
      - "8761:8761"
    network_mode: "host"
    
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=streamworx_test
      - MYSQL_ROOT_PASSWORD=test12345
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  db_seeder:
    image: mysql:8.0
    volumes:
      - ./db_init.sql:/db_init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    entrypoint: [ "bash", "-c", "sleep 10 && mysql --user=root --host=db --password=test12345 --port=3306 streamworx_test < /db_init.sql && exit" ]
    depends_on:
      - db
  post-service:
    image: streamworx-posts:latest
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.jpa.hibernate.ddl-auto" : "none",  
      "spring.datasource.url" : "jdbc:mysql://localhost:3306/streamworx_test",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "test12345",
      "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
      "spring.jpa.show-sql" : "true"
      }'
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
      - db
  main-service:
    image: streamworx-main-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port"  : "8081"
      }'
    ports:
      - "8081:8081"
    network_mode: "host"
    depends_on:
      - registration-service
      - post-service
      - cache 
    
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local
